### PR TITLE
Feature/fixtures install #71

### PR DESCRIPTION
**Pull request by 4lm**
Hi @nesnoj,

please review this pull request. It solves the installation issue described in #71 and also contains a commit for adding the custom command: get_fixtures_stemp_abw. Please review the pull request #76 first, because this pull request also contains all commits of pull request #76.

Usage custom command: python manage.py get_fixtures_stemp_abw

Attention: Right now, it downloads (i) an empty JSON fixture zip file from the zenodo data platform and (ii) also tries to download a zip file that doesn't exist to trigger an error message. If you're done with the real data export to zenodo, please add the URL to `FILES_URLS` list in `stemp_abw/management/commands/get_fixtures_stemp_abw.py` and delete the two given ones.

Thx!

Edit: The library "requests" is needed (I did put it as a requirement in requirements.txt)

### CODE REVIEW

**Review by nesnoj — CHANGES_REQUESTED** [review]
Please amend docs and perform trail run (fresh install from scratch)

**EDIT:** I adjusted the [install docs](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/feature/fixtures-install/doc/installation_and_setup.rst), the last section is for the data deployment..

**Comment by nesnoj** [comment]
I uploaded the current fixture to zenodo and updated the link in the deploy script. Also, I added some lines to the docs.
Good luck installing from scratch! :)

PS: I also copied a dump to your temp

**Comment by 4lm** [comment]
@nesnoj, please review this pull request again, the installation docs are now complete - thx!

**Comment by nesnoj** [comment]
Thx a lot @4lm, love this solution :heart:

**Review by nesnoj — APPROVED** [review]

**Pull request merged**
