### PR TITLE
Feature/improve loading time

### PR DESCRIPTION
**Pull request by 4lm**
Hi @nesnoj,

please review this pull request. I improved loading time by activate caching and refactored the code to reduce the use of Django's templating logic and variables in the JS code part in map.html.

If you first merge the pull request Feature/choroplethmap to the "dev" branch, this pull request should merge automatically.

Regards,
Alexis

### CODE REVIEW

**Comment by nesnoj** [comment]
Major merging problems, please fix and create new PR into updated dev.

**Comment by 4lm** [comment]
Hi @nesnoj,

I solved the merge conflicts by dropping most of my JS changes in branch "feature/improve-loading-time", but keeping the caching solution of the branch. Because commits are added even after a pull request of a branch is made into the pull request, I reopened this pull request instead of openening a new one (to have all history in one place).

Edit: @nesnoj, feel free to merge this pull request into dev after reviewing it.

**Comment by nesnoj** [comment]
Thanks a lot for the speedup!
Works well, I only moved the timeout setting to app_settings.
I'll merge it.

It's a pity you dropped the changes in the data passing (JS instead of Django vars), do you see a chance that you could re-implement this later? Could you please open a new issue on this to make sure we do not forget about this improvement? Cheers

**Comment by 4lm** [comment]
> It's a pity you dropped the changes in the data passing (JS instead of Django vars), do you see a chance that you could re-implement this later? Could you please open a new issue on this to make sure we do not forget about this improvement? Cheers

Thanks for merging. Yes, I will open an issue! I couldn't get my head around it (I had some side effects and stuff wasn't loading properly), so after 45 minutes I decided to merge the old version, because it delivers the same results.

**Pull request merged**
